constants:
  file:
    directory : /home/download/




Spring:
  datasource:
#    url: jdbc:log4jdbc:mariadb://112.222.157.157:5012/first_project
    url: jdbc:mariadb://127.0.0.1:3306/2025_1st_Project_BE
    username: root
    password: 921218
    driver-class-name: org.mariadb.jdbc.Driver


mybatis:
  mapper-locations: mappers/**/*.xml

  configuration:
    map-underscore-to-camel-case: true